"""Platform knowledge: macOS + Python CLI + pyproject.toml.

Operational knowledge for Python CLI tools built with pyproject.toml
on macOS.  Covers virtual environment creation, editable installs,
entry points, and the common ways Claude Code gets these wrong.

Registered at import time via :func:`~duplo.platforms.schema.register`.
"""

from __future__ import annotations

from duplo.platforms.schema import PlatformProfile, ScaffoldFile, register

# ---------------------------------------------------------------------------
# run.sh template
# ---------------------------------------------------------------------------

_RUN_SH = """\
#!/bin/bash
# Create venv (if missing), install in editable mode, and run.
# Usage: ./run.sh [args...]
#
# This script is the ONLY way to run the project. It guarantees:
#   1. A venv exists at .venv/
#   2. The package is installed in editable mode (pip install -e .)
#   3. The CLI entry point is available
#
# Pass arguments through to the CLI:
#   ./run.sh --help
#   ./run.sh convert input.csv

set -euo pipefail

VENV_DIR=".venv"
PYTHON="$VENV_DIR/bin/python"
PIP="$VENV_DIR/bin/pip"

# Create venv if it does not exist.
if [[ ! -d "$VENV_DIR" ]]; then
    echo "Creating virtual environment..."
    python3 -m venv "$VENV_DIR"
fi

# Editable install (fast no-op if already installed and unchanged).
"$PIP" install -e ".[dev]" --quiet 2>/dev/null || "$PIP" install -e . --quiet

# Run via python -m so it works even if entry point scripts
# have not been regenerated yet.
"$PYTHON" -m {project_name} "$@"
"""

# ---------------------------------------------------------------------------
# .gitignore entries
# ---------------------------------------------------------------------------

_GITIGNORE_ENTRIES = [
    ".venv/",
    "__pycache__/",
    "*.pyc",
    "*.pyo",
    "*.egg-info/",
    "dist/",
    "build/",
    ".eggs/",
    ".pytest_cache/",
    ".ruff_cache/",
    ".mypy_cache/",
    ".DS_Store",
]

# ---------------------------------------------------------------------------
# Profile
# ---------------------------------------------------------------------------

_PROFILE = PlatformProfile(
    id="macos-python-cli",
    display_name="macOS + Python CLI + pyproject.toml",
    match_platform=["desktop", "macos", "cli"],
    match_language=["python"],
    match_any_preference=[
        "pyproject",
        "pyproject.toml",
        "cli",
        "command line",
    ],
    planner_rules=[
        (
            "Every task that runs the CLI MUST use ./run.sh, never "
            "python <file>.py or the bare entry point name. run.sh "
            "guarantees the venv exists and the package is installed."
        ),
        (
            "Phase 0 scaffold MUST NOT recreate run.sh or .gitignore -- "
            "these are pre-generated by duplo. Phase 0 tasks should "
            "create pyproject.toml, the package directory with "
            "__init__.py and __main__.py, then run ./run.sh --help "
            "to verify the entry point works."
        ),
        (
            "Always use pyproject.toml for project metadata, not "
            "setup.py or setup.cfg. Declare the CLI entry point "
            "under [project.scripts]."
        ),
        (
            "Test tasks MUST run via .venv/bin/pytest (or "
            "./run.sh -m pytest), never bare pytest, to ensure "
            "the correct venv is active."
        ),
        (
            "Do not generate tasks that create a venv or pip install "
            "manually. run.sh handles this. Tasks should assume "
            "run.sh has been executed at least once."
        ),
        (
            "When adding dependencies, add them to pyproject.toml "
            "[project.dependencies], not requirements.txt. Then "
            "re-run ./run.sh to pick them up."
        ),
    ],
    claude_md_rules=[
        (
            "NEVER run python <file>.py directly or call the CLI "
            "entry point by name outside the venv. Always use "
            "./run.sh which creates the venv, installs the package "
            "in editable mode, and runs via python -m."
        ),
        ("Do NOT recreate or overwrite run.sh or .gitignore -- these are managed by duplo."),
        (
            "Do NOT create a venv manually, do NOT run pip install "
            "manually. run.sh handles all of this. If you need a "
            "new dependency, add it to pyproject.toml and re-run "
            "./run.sh."
        ),
        (
            "Use pyproject.toml for ALL project configuration. "
            "Do not create setup.py, setup.cfg, or requirements.txt."
        ),
        ("Run tests via .venv/bin/pytest, never bare pytest."),
        (
            "The package MUST have a __main__.py so that "
            "python -m <package> works. This is what run.sh calls."
        ),
    ],
    scaffold_files=[
        ScaffoldFile(
            path="run.sh",
            content=_RUN_SH,
            executable=True,
        ),
    ],
    prerequisites=[
        "Python 3.11+ (via Homebrew or system python3)",
        "pip (ships with Python 3.11+)",
    ],
    failure_modes=[
        (
            "Running python <file>.py without activating the venv: "
            "ImportError on every third-party dependency."
        ),
        (
            "Creating requirements.txt instead of declaring dependencies "
            "in pyproject.toml: makes editable install incomplete."
        ),
        (
            "Forgetting __main__.py: python -m <package> fails with "
            "'No module named <package>.__main__'."
        ),
        (
            "Running bare pytest outside the venv: picks up system "
            "pytest (if any) which cannot see project dependencies."
        ),
        (
            "Using setup.py alongside pyproject.toml: build system "
            "confusion, editable install may silently use the wrong one."
        ),
        (
            "Hardcoding python3.11 or python3.12 in scripts instead "
            "of using .venv/bin/python: breaks when Python minor "
            "version changes."
        ),
    ],
    bootstrap_steps=[
        "python3 -m venv .venv",
        ".venv/bin/pip install -e '.[dev]'",
    ],
    gitignore_entries=_GITIGNORE_ENTRIES,
)

register(_PROFILE)
