"""Platform knowledge: macOS + SwiftUI + Swift Package Manager.

This is the operational knowledge that bridges "code that compiles"
and "a running macOS GUI app you can see and interact with."  It
encodes the painful lessons from building SwiftUI apps via Claude
Code in -p mode.

Registered at import time via :func:`~duplo.platforms.schema.register`.
"""

from __future__ import annotations

from duplo.platforms.schema import PlatformProfile, ScaffoldFile, register

# ---------------------------------------------------------------------------
# run.sh template
# ---------------------------------------------------------------------------
# {project_name} is expanded by the scaffold writer.

_RUN_SH = """\
#!/bin/bash
# Build and launch the macOS app bundle.
# Usage: ./run.sh [--release]
#
# SwiftUI apps MUST run inside an app bundle to display windows.
# Running .build/debug/<binary> directly will silently produce
# no UI.  This script:
#   1. Builds via swift build
#   2. Creates a minimal .app bundle
#   3. Copies the binary into the bundle
#   4. Launches the bundle with `open`

set -euo pipefail

PRODUCT_NAME="{project_name}"
BUILD_CONFIG="debug"
if [[ "${{1:-}}" == "--release" ]]; then
    BUILD_CONFIG="release"
fi

echo "Building ($BUILD_CONFIG)..."
swift build -c "$BUILD_CONFIG"

BINARY=".build/$BUILD_CONFIG/$PRODUCT_NAME"
if [[ ! -f "$BINARY" ]]; then
    echo "ERROR: Binary not found at $BINARY"
    echo "Check that Package.swift declares an executable target named $PRODUCT_NAME"
    exit 1
fi

APP_BUNDLE="$PRODUCT_NAME.app"
MACOS_DIR="$APP_BUNDLE/Contents/MacOS"
mkdir -p "$MACOS_DIR"

# Minimal Info.plist -- enough for SwiftUI to create a window.
cat > "$APP_BUNDLE/Contents/Info.plist" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>$PRODUCT_NAME</string>
    <key>CFBundleIdentifier</key>
    <string>com.duplo.$PRODUCT_NAME</string>
    <key>CFBundleName</key>
    <string>$PRODUCT_NAME</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleVersion</key>
    <string>1.0</string>
    <key>LSMinimumSystemVersion</key>
    <string>14.0</string>
    <key>NSHighResolutionCapable</key>
    <true/>
</dict>
</plist>
PLIST

cp "$BINARY" "$MACOS_DIR/$PRODUCT_NAME"

echo "Launching $APP_BUNDLE..."
open "$APP_BUNDLE"
"""

# ---------------------------------------------------------------------------
# .gitignore entries
# ---------------------------------------------------------------------------

_GITIGNORE_ENTRIES = [
    ".build/",
    "*.app/",
    ".swiftpm/",
    "Package.resolved",
    ".DS_Store",
    "xcuserdata/",
    "DerivedData/",
]

# ---------------------------------------------------------------------------
# Profile
# ---------------------------------------------------------------------------

_PROFILE = PlatformProfile(
    id="macos-swiftui-spm",
    display_name="macOS + SwiftUI + Swift Package Manager",
    match_platform=["desktop", "macos"],
    match_language=["swift", "swift/swiftui", "swiftui"],
    match_any_preference=[
        "swift package manager",
        "spm",
        "macos 14",
        "macos 15",
    ],
    planner_rules=[
        (
            "Every task that verifies the app runs MUST use ./run.sh, "
            "never .build/debug/<name> directly. SwiftUI apps require "
            "an app bundle context to display windows."
        ),
        (
            "Phase 0 scaffold MUST NOT recreate run.sh or .gitignore -- "
            "these are pre-generated by duplo. Phase 0 tasks should "
            "create Package.swift, the Sources/ directory structure, "
            "and a minimal @main App struct, then run ./run.sh to verify."
        ),
        (
            "Do not generate tasks that launch the binary and wait for "
            "it to exit as a verification step. GUI apps do not exit on "
            "their own. Instead, generate: run ./run.sh, visually confirm "
            "the window appears, then Cmd-Q to quit."
        ),
        (
            "SPM resource bundles require Bundle.module -- do not use "
            "Bundle.main for resources declared in Package.swift."
        ),
        (
            "If a task adds resources (images, JSON, etc.), it MUST also "
            "add a .process() or .copy() rule in Package.swift targets "
            "resources array."
        ),
        (
            "For macOS 14+, prefer the Observation framework (@Observable) "
            "over Combine/ObservableObject. Do not mix the two patterns."
        ),
    ],
    claude_md_rules=[
        (
            "NEVER run .build/debug/<name> directly. SwiftUI apps need "
            "a bundle context (Info.plist + .app structure) to display "
            "windows. Always use ./run.sh which builds, creates the "
            "bundle, and launches with open."
        ),
        (
            "NEVER launch the binary and wait for it to return as a "
            "test. macOS GUI apps do not exit on their own. Use: "
            "./run.sh to launch, then kill the process or Cmd-Q."
        ),
        (
            "Do NOT recreate or overwrite run.sh or .gitignore -- these "
            "are managed by duplo."
        ),
        (
            "When adding resources to SPM targets, always use "
            "Bundle.module (not Bundle.main) and add a matching "
            ".process() or .copy() entry in Package.swift."
        ),
        (
            "For macOS 14+, use @Observable (Observation framework), "
            "not ObservableObject/Published (Combine). Do not mix "
            "the two patterns in the same project."
        ),
        (
            "App signing: for local development, do not add signing "
            "configuration. swift build does not code-sign by default "
            "and that is fine for development. run.sh handles launching "
            "unsigned bundles."
        ),
    ],
    scaffold_files=[
        ScaffoldFile(
            path="run.sh",
            content=_RUN_SH,
            executable=True,
        ),
    ],
    prerequisites=[
        "Xcode 15+ with command line tools (xcode-select --install)",
        "Swift 5.9+ (ships with Xcode 15+)",
    ],
    failure_modes=[
        (
            "Running .build/debug/<name> directly: produces no window. "
            "SwiftUI requires Info.plist and app bundle structure."
        ),
        (
            "Waiting for a GUI binary to exit: infinite hang. macOS apps "
            "run until explicitly quit."
        ),
        (
            ".build/ directory not in .gitignore: pollutes git status "
            "and breaks mcloop's post-task git checks."
        ),
        (
            "Using Bundle.main instead of Bundle.module for SPM "
            "resources: resources not found at runtime."
        ),
        (
            "Mixing @Observable and ObservableObject in the same "
            "view hierarchy: unpredictable update behavior."
        ),
    ],
    bootstrap_steps=[
        "swift package resolve",
    ],
    gitignore_entries=_GITIGNORE_ENTRIES,
)

register(_PROFILE)
