"""Format PlatformProfile data for injection into prompts and CLAUDE.md.

Pure functions, no I/O.  Each function takes a list of profiles and
returns a string.
"""

from __future__ import annotations

from duplo.platforms.schema import PlatformProfile


def format_planner_system_addendum(profiles: list[PlatformProfile]) -> str:
    """Format platform rules for appending to the planner system prompt.

    Returns an empty string if *profiles* is empty.
    """
    if not profiles:
        return ""

    parts: list[str] = [
        "",
        "## Platform-specific rules (from duplo platform knowledge)",
        "",
        "These rules are MANDATORY. Every task you generate MUST comply.",
        "",
    ]

    for profile in profiles:
        parts.append(f"### {profile.display_name}")
        parts.append("")
        for rule in profile.planner_rules:
            parts.append(f"- {rule}")
        parts.append("")

        if profile.failure_modes:
            parts.append("Common failure modes to AVOID:")
            parts.append("")
            for fm in profile.failure_modes:
                parts.append(f"- {fm}")
            parts.append("")

        if profile.prerequisites:
            parts.append("Prerequisites (mention in Phase 0 description):")
            parts.append("")
            for prereq in profile.prerequisites:
                parts.append(f"- {prereq}")
            parts.append("")

    return "\n".join(parts)


def format_claude_md_section(profiles: list[PlatformProfile]) -> str:
    """Format a ``## Platform rules`` section for CLAUDE.md.

    Returns an empty string if *profiles* is empty.
    """
    if not profiles:
        return ""

    parts: list[str] = [
        "## Platform rules (auto-generated by duplo -- do not edit)",
        "",
    ]

    for profile in profiles:
        parts.append(f"### {profile.display_name}")
        parts.append("")
        for rule in profile.claude_md_rules:
            parts.append(f"- {rule}")
        parts.append("")

        if profile.failure_modes:
            parts.append("Known failure modes:")
            parts.append("")
            for fm in profile.failure_modes:
                parts.append(f"- {fm}")
            parts.append("")

    return "\n".join(parts)


def format_local_overrides(local_md_content: str) -> str:
    """Format local.md content for injection into prompts and CLAUDE.md.

    Returns an empty string if *local_md_content* is blank.
    """
    stripped = local_md_content.strip()
    if not stripped:
        return ""
    return "\n## Local overrides (from local.md -- project-specific)\n\n" + stripped + "\n"
